### ISSUE TITLE
Timeout and errors while sending command

### ISSUE THREAD

**Issue by AshWan13** [Terabee/teraranger_array_tutorials#1]
Hi, I have been trying to set-up terabee multiflex sensors and had encountered this error.
Hope to get some help in solving this. Thank you!

** Just some background information, I have been trying to modify from the kobuki_bringup launch file and adapting the use of the multiflex to the application of my robot.

![image](https://user-images.githubusercontent.com/49274559/55558502-cd821300-571e-11e9-993a-5b335307c8e7.png)

**Comment by pl-kabaradjian** [comment]
Hello @AshWan13 ,

This error means that the Multiflex didn't answer within 2 sec after sending the command that activates sensors on the strip (which can happen in rare cases). However, as long as you don't get "reading timeout" this shouldn't impact the measurements collection.

Can you check that you get data in /ranges? (rostopic echo /ranges)

However, from what I see in your screenshot, it seems that your TF tree (which is created in the URDF) is not setup properly. This TF tree is mandatory to be able to build LaserScans and PointClouds as it is where sensor positions are defined. You will not get any conversion until a proper TF tree is setup.
More info on those topics:
- http://wiki.ros.org/tf
- https://github.com/Terabee/teraranger_description#using-teraranger_description

**Comment by AshWan13** [comment]
Yes, thanks for the response!

I am able to get data in /ranges.
Am having some trouble resolving the TF tree issue (mainly).

**Comment by AshWan13** [comment]
Hi, I have tried to fix up TF tree proper, the warning messages have changed. However, I am still having some difficulties understand how a proper tf tree should be structured. Are there any sample codes examples where I am able to take reference from? 

![image](https://user-images.githubusercontent.com/49274559/56120169-30d23780-5fa0-11e9-85b3-434b3f1e9e12.png)
![image](https://user-images.githubusercontent.com/49274559/56120129-1e57fe00-5fa0-11e9-940e-78a9f2e58e9e.png)
![image](https://user-images.githubusercontent.com/49274559/56120182-3af43600-5fa0-11e9-9728-e7e55936d25b.png)
![image](https://user-images.githubusercontent.com/49274559/56120197-40ea1700-5fa0-11e9-8763-8df6ff108926.png)

**Comment by pl-kabaradjian** [comment]
Hello @AshWan13 ,
I think you're getting closer to the solution ;).
When you include custom-sensor-setup.urdf.xacro, don't forget to actually call the xacro. You can do this the same way you call "<robotino_body/>", like this :
`<custom-sensor-setup/>`
In any case, to help debugging TF issue we recommend using **rqt** software with the TF-tree visualization plugin.

**Comment by AshWan13** [comment]
Thank you!
Can I also ask if it is expected that the point cloud is not visible on rviz? 

![Screenshot from 2019-04-16 16-58-15](https://user-images.githubusercontent.com/49274559/56196177-e963ae00-6068-11e9-974e-1d9c4be3cf4d.png)

Thanks again, your responses were very helpful!
